server:
  port: 80

spring:
  datasource:
    url: "jdbc:mysql://basket_database:3306/basket_service"
    username: "root"
    password: "root"

  rabbitmq:
    host: "event_bus"
    port: "5672"
    username: "guest"
    password: "guest"
    virtual-host: "/"

