version: '2'
services:

  #############################################################################
  # See: https://hub.docker.com/_/java/
  fcproxy_service:
    build: .

    restart: "always"

    container_name: "event_bus_fcproxy_service"

    ports:
      - "8080:80"

    volumes:
      - "../FCProxyService/target/fcproxy-service-0.0.1-SNAPSHOT.jar:/app.jar"

    networks:
      - "event_bus_network"

    links:
      - "event_bus"


  #############################################################################
  # See: https://hub.docker.com/_/java/
  user_service:
    build: .

    restart: "always"

    container_name: "event_bus_user_service"

    ports:
      - "8081:80"

    volumes:
      - "../UserService/target/user-service-0.0.1-SNAPSHOT.jar:/app.jar"

    networks:
      - "event_bus_network"

    links:
      - "user_database"
      - "event_bus"


  #############################################################################
  # See: https://hub.docker.com/_/java/
  basket_service:
    build: .

    restart: "always"

    container_name: "event_bus_basket_service"

    ports:
      - "8082:80"

    volumes:
      - "../BasketService/target/basket-service-0.0.1-SNAPSHOT.jar:/app.jar"

    networks:
      - "event_bus_network"

    links:
      - "basket_database"
      - "event_bus"


  #############################################################################
  # See: https://hub.docker.com/_/mysql
  user_database:
    extends:
      file: docker-compose-dev.yml
      service: user_database


  #############################################################################
  # See: https://hub.docker.com/_/mysql
  basket_database:
    extends:
      file: docker-compose-dev.yml
      service: basket_database


  #############################################################################
  # See: https://hub.docker.com/r/_/rabbitmq/
  event_bus:
    extends:
      file: docker-compose-dev.yml
      service: event_bus

networks:
  event_bus_network:
    driver: bridge
