server:
  port: 8080

spring:
  datasource:
    url: "jdbc:mysql://user_database:3306/user_service"
    username: "root"
    password: "root"

  rabbitmq:
    host: "event_bus"
    port: "5672"
    username: "guest"
    password: "guest"
    virtual-host: "/"

