spring:
  profiles:
    active: dev

  datasource:
    continue-on-error: false

  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQLDialect"
        format_sql: "true"
        id:
          new_generator_mappings: "false"

eventbus:
  objects:
    exchange: "x.privalia.event-bus.vpi-global"
    queue: "q.privalia.event-bus.vpi-global.vpi-user"
