server:
  port: 8081

spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/user_service"
    username: "root"
    password: "root"

  rabbitmq:
    host: "localhost"
    port: "5672"
    username: "guest"
    password: "guest"
    virtual-host: "/"
